/**
 * CANON.md Template
 * 
 * Resonance Anchor (Single Source of Truth)
 * - Canonical parameter set
 * - Invariants
 * - Interfaces
 * - Checks
 */

import type { SpiritData } from '../types';
import { SOULFORGE_VERSION } from '../spirit';

export function renderCanonMd(canon: SpiritData, language: 'en' | 'de' = 'en'): string {
  if (language === 'de') {
    return renderGerman(canon);
  }
  return renderEnglish(canon);
}

function renderEnglish(canon: SpiritData): string {
  return `# CANON.md — Resonance Anchor (Single Source of Truth)

## Intent
This file is the canonical parameter set. All other files must remain consistent with it.

## Invariants
- Canon values change only by explicit user decision.
- If Canon changes, apply change-impact-map to update dependent files.

## Canon

### Identity
- **agent_name**: ${canon.agentName}
- **agent_title**: ${canon.agentTitle}
- **agent_mode**: ${canon.agentMode}
- **domain_focus**: ${canon.domainFocus}

### Tone
- **precision**: ${canon.tone.precision}
- **method**: ${canon.tone.method}
- **directness**: ${canon.tone.directness}

### Autonomy
- **action_mode**: ${canon.autonomy.actionMode}
- **approval_threshold**: ${canon.autonomy.approvalThreshold}

### Surprise
- **appetite**: ${canon.surprise.appetite}
- **cadence**: ${canon.surprise.cadence}
- **boundaries**: ${canon.surprise.boundaries}

### Truth Policy
- **truth_policy**: ${canon.truthPolicy}
- **negative_constraints_ref**: SOUL.md

### Output
- **format**: ${canon.output.format}
- **explanations**: ${canon.output.explanations}
- **confidence_display**: ${canon.output.confidenceDisplay}

### Addressing
- **form**: ${canon.addressing.form}
- **language**: ${canon.addressing.language}
- **timezone**: ${canon.addressing.timezone}

### Stop Words
${canon.stopWords.map(w => `- ${w}`).join('\n') || '- None defined'}

## Interfaces

### SOUL.md must implement:
- \`truth_policy\` + \`negative_constraints\`

### IDENTITY.md must match:
- \`agent_name\`, \`agent_title\`, \`tone\`

### USER.md must match:
- \`autonomy\` + \`surprise\` + address/output preferences

### HEARTBEAT.md must operationalize:
- \`surprise.cadence\` and respect \`autonomy\`

### SHIELD.md must be consistent with:
- \`approval_threshold\` and constitutional prohibitions

## Checks
- If any file contradicts Canon: fix the file, not Canon (unless user explicitly changed Canon).
- Run resonance-gates.json validation on any Canon change.

---
*Generated by OpenClaw SoulForge v${SOULFORGE_VERSION}*
`;
}

function renderGerman(canon: SpiritData): string {
  const modeLabels: Record<string, string> = {
    'sidekick': 'Sidekick (Discovery)',
    'chief-of-staff': 'Chief of Staff (Execution)',
    'coach': 'Coach (Accountability)',
  };

  const domainLabels: Record<string, string> = {
    'engineering': 'Engineering',
    'product': 'Product',
    'ops': 'Operations',
    'research': 'Research',
    'sales': 'Sales',
    'legal': 'Legal',
    'finance': 'Finance',
    'people': 'People',
    'mixed': 'Mixed',
  };

  return `# CANON.md — Resonance Anchor (Single Source of Truth)

## Intent (Absicht)
Diese Datei ist der kanonische Parametersatz. Alle anderen Dateien müssen konsistent damit bleiben.

## Invariants (Invarianten)
- Canon-Werte ändern sich nur durch explizite Nutzerentscheidung.
- Falls Canon sich ändert, change-impact-map auf abhängige Dateien anwenden.

## Canon (Kanon)

### Identity (Identität)
- **agent_name**: ${canon.agentName}
- **agent_title**: ${canon.agentTitle}
- **agent_mode**: ${modeLabels[canon.agentMode] || canon.agentMode}
- **domain_focus**: ${domainLabels[canon.domainFocus] || canon.domainFocus}

### Tone (Ton)
- **precision**: ${canon.tone.precision}
- **method**: ${canon.tone.method}
- **directness**: ${canon.tone.directness}

### Autonomy (Autonomie)
- **action_mode**: ${canon.autonomy.actionMode}
- **approval_threshold**: ${canon.autonomy.approvalThreshold}

### Surprise (Überraschung)
- **appetite**: ${canon.surprise.appetite}
- **cadence**: ${canon.surprise.cadence}
- **boundaries**: ${canon.surprise.boundaries}

### Truth Policy (Wahrheitspolitik)
- **truth_policy**: ${canon.truthPolicy}
- **negative_constraints_ref**: SOUL.md

### Output
- **format**: ${canon.output.format}
- **explanations**: ${canon.output.explanations}
- **confidence_display**: ${canon.output.confidenceDisplay}

### Addressing (Ansprache)
- **form**: ${canon.addressing.form}
- **language**: ${canon.addressing.language}
- **timezone**: ${canon.addressing.timezone}

### Stop Words
${canon.stopWords.map(w => `- ${w}`).join('\n') || '- Keine definiert'}

## Interfaces (Schnittstellen)

### SOUL.md muss implementieren:
- \`truth_policy\` + \`negative_constraints\`

### IDENTITY.md muss übereinstimmen mit:
- \`agent_name\`, \`agent_title\`, \`tone\`

### USER.md muss übereinstimmen mit:
- \`autonomy\` + \`surprise\` + Ansprache/Output-Präferenzen

### HEARTBEAT.md muss operationalisieren:
- \`surprise.cadence\` und \`autonomy\` respektieren

### SHIELD.md muss konsistent sein mit:
- \`approval_threshold\` und konstitutionellen Prohibitionen

## Checks (Prüfungen)
- Falls eine Datei Canon widerspricht: Die Datei korrigieren, nicht Canon (außer Nutzer hat Canon explizit geändert).
- Resonance-gates.json Validierung bei jeder Canon-Änderung ausführen.

---
*Generiert von OpenClaw SoulForge v${SOULFORGE_VERSION}*
`;
}
